### ISSUE TITLE
TLDR;

### ISSUE THREAD

**Issue by pctechkid** [demon-rem/kodi-strm#2]
Too many prior setups/configurations needed to run before you can fully use the addon. Unlike the existing addon, the only thing you have to do is to is login your account and you're good to go, the addon does the setups by itself!

Not user-friendly if I may say.

**Comment by demon-rem** [comment]
> Too many prior setups/configurations needed to run before you can fully use the addon.

Agreed, creating a google project is an additional step. To be fair, this is a one-time setup, nevertheless, this can be time consuming for new users.

On the other hand, when you use the Google Drive add-on, you grant a third-party full (read) access to ***all*** your files on Google Drive. For some people (including myself), this is a big downside - I'd rather spend an additional twenty minutes to use my own project, than let some random person have full read (and/or write) access to my drive.

Which is why I went ahead with the current setup - to have users use their own credentials instead of granting access to someone else (me in this case).

With that being said, I do agree with you - this might be inconvenient for some users. In a future commit, I do plan to ***add*** an option to use default credentials hard coded in the script (that is, users will be granting access to a project that I own - avoiding the inconvenience of having to create one, which is what the Kodi add-on does). 

Hope that satisfies your query regarding my design choices so far :)

**Comment by pctechkid** [comment]
Nevertheless, I would still give this addon a shot. I'd like to try this out myself and see the differences between yours and the existing addon. Anyway, you did a great job for working on this. Mad respect goes to you 👍
