### ISSUE TITLE
skip files and folder with same name

### ISSUE THREAD

**Issue by khazardstudent** [demon-rem/kodi-strm#27]
, while scanning large library if there are two folders with same name it stops, it there an custom arguments to skip folder if already exist.

**Comment by demon-rem** [comment]
As for "_skip files and folders with same name_" - I'm not really sure what you're talking about. This project will not auto-update, or watch for changes on the drive folder. As such, whenever you use this script, it will _intentionally_ iterate through each directory - and if the target directory already exists, the script will delete it.

Regarding "_if there are two folders with same name it stops_". Yes, if your drive has two folders/files with the same name together, the script will run into an error. This is intentional behaviour. 

Your suggestion to add a custom argument to suppress this is possible. I'll probably implement this in a future update. Possibly a `--suppress-errors` flag or something similar. Thanks for the suggestion :)
