### ISSUE TITLE
I can't login to Google Drive from ssh terminal

### ISSUE THREAD

**Issue by wowwoo** [demon-rem/kodi-strm#33]
I installed successfuly I hope
I did download credentials.json to same as folder strm-generator.py inclued
I authenticated, logged in, and allowed according to the URL in the terminal, but I am redirected to localhost and can't do anything

How can I solve it?

**Comment by demon-rem** [comment]
Hi, this script internally uses `google-auth-oauthlib` for authentication - which should support clients over SSH too.

The easiest solution will be to login *locally* using this script - and then, copy the `token.pickle` file generated to the root folder of your remote client. This should allow you to skip the login process entirely.

Alternatively, based on what you said, the problem seems to be with redirection after a successful login - strictly speaking, this part is optional. Check if the root folder contains a file named `token.pickle`, if it does, the login process was successful, and just the part of redirecting you failed. If not, you can login locally and copy the `token.pickle` over (as explained above).

**Comment by wowwoo** [comment]
Thank you for your answer but I no luck my Windows PC on Linux shell. It was my fault I don't know much linux things. I'll try it many times, thank you!

**Comment by demon-rem** [comment]
If you want an easy solution, you can just make a fork of this repository, and add the `token.pickle` file to your fork.

Basically, complete the login process locally, use the command `git add -f token.pickle` to add the token file to staging, then commit and push to your fork.

After that, you can simply clone your fork (which will now also include the token file) and deploy this script to remote clients.

Note: If you're doing this, make sure that your fork is **private** to ensure that you don't expose your token.

P.S. Closing this issue - at this point, this is a conversation about how to deploy configs to remote clients securely, than an issue related to this repository. If you have any other issues, feel free to reopen this issue (or a new one).
